### PR TITLE
(Feature) Add Registry contract

### PR DESCRIPTION
**Pull request by fvictorio**
This adds a Registry contract that would allow us to know what ICO contracts were created by a given address.

Since, as far as I know, Solidity doesn't support array of strings as function parameters, we'll need to make a transaction for each contract address that we want to associate with the user.

### CODE REVIEW

**Comment by igorbarinov** [comment]
Please add tests
You can see examples how we do tests here
https://github.com/oraclesorg/poa-network-consensus-contracts

**Comment by fvictorio** [comment]
@igorbarinov Done.

**Review by vbaranov — COMMENTED** [review]
@fvictorio I would suggest this registry contract
```
pragma solidity ^0.4.18;

contract Registry {
    
    mapping (address => DeployedCrowdsale[]) public deployedCrowdsales;
    
    struct DeployedCrowdsale {
        address crowdsaleAddr;
    }
    
    function set(address addr) public {
        deployedCrowdsales[msg.sender].push(DeployedCrowdsale(addr));
    }
    
    function getCrowdsalesLength() public view returns(uint) {
        return deployedCrowdsales[msg.sender].length;
    }
    
    function getCrowdsale(uint pos) public view returns(address crowdsaleAddr) {
        DeployedCrowdsale storage deployedCrowdsale = deployedCrowdsales[msg.sender][pos];
        crowdsaleAddr = deployedCrowdsale.crowdsaleAddr;
    }
}
```
Incentives:
1. We can get all crowdsale data by knowing only crowdsale address. Thus, I don't think we need string `extraData` param. Or maybe I missed something. Please, clarify, if we need it.
2. Struct should contain id of the network to be able to filter contracts on the ICO Wizard side.
3.  We need to store length of users crowdsales to be able to iterate on the ICO Wizard side.

What do you think @fvictorio ?

**Comment by igorbarinov** [comment]
I didn’t get 2. 
Registry will be deployed on each network. Only contract from a network will be used on each instance.

**Comment by vbaranov** [comment]
I see. Fixed Registry code above: networkID is removed from struct.

**Comment by fvictorio** [comment]
The `extraData` is a way of making this future proof. For example, if the ABI of the crowdsale contract is modified, we can store a version number in that string. That way the app would be able to know which ABI to use. There could be other potential uses, the main point is not needing to modify the registry contract but being able to update the crowdsale contracts.

I agree with 3, I'm going to add a getter to obtain the number of deployed contracts given an address.

**Comment by fvictorio** [comment]
Oh, I see you also removed the `id`. That is also a way to know which ABI to use. We could have just the `extraData` string and have the identifier there.

I'm curious, how would you know which ABI to use if you only had the address? The only thing I can think of is comparing the contract data with each available `bin`.

**Comment by vbaranov** [comment]
>I'm curious, how would you know which ABI to use if you only had the address? The only thing I can think of is comparing the contract data with each available bin.

Let's ask user for ABI of contract he chose in the list? He has it in the downloaded file. And if user don't know ABI, use the latest ABI by default.

**Comment by fvictorio** [comment]
Ok, we'll only save addresses, right? No need for a struct then, I'll use an array of addresses.

**Comment by fvictorio** [comment]
Updated code and tests.

**Comment by vbaranov** [comment]
>Ok, we'll only save addresses, right? No need for a struct then, I'll use an array of addresses.

Yes, addresses storage is enough, imo. We should be able to get all crowdsale data from contracts.

**Review by vbaranov — APPROVED** [review]

**Comment by fvictorio** [comment]
@igorbarinov, can you review this, so that it has the two necessary approvals?

**Comment by igorbarinov** [comment]
@rstormsf please review the PR

**Comment by rstormsf** [comment]
@fvictorio it looks damn simple and good. So I assume you are going to have each Registry per each chain (kovan, sokol, poa, mainnet, ropsten, rinkeby)

**Review by rstormsf — APPROVED** [review]

**Comment by fvictorio** [comment]
Yes, we added an environment variable that holds the addresses for each registry (see https://github.com/poanetwork/ico-wizard/blob/register-created-contracts/.env.example)

**Review by rstormsf — CHANGES_REQUESTED** [review]
please add an event when you call method `add`
@fvictorio 
```js
event Added(address indexed sender);
Added(msg.sender);
```

**Comment by igorbarinov** [comment]
@rstormsf why do we need this event?

**Comment by rstormsf** [comment]
@igorbarinov how else you are going to know how many total number of people has ever deployed ICO via wizard?

It's much easier to parse data via event

**Comment by fvictorio** [comment]
Sure, I'll add the event, thanks.

**Comment by fvictorio** [comment]
Done, although I'm not sure if that is the best way. Shouldn't we log both the `msg.sender` and the added address?

**Comment by rstormsf** [comment]
@fvictorio sure why not

**Comment by fvictorio** [comment]
Updated. This should be ready now.

**Comment by fvictorio** [comment]
I'm going to merge this because it's blocking poanetwork/ico-wizard#404. The last change (the only one that wasn't reviewed yet) is very low risk and it's tested.

**Comment by fvictorio** [comment]
Oh, right, I can't merge in this repo. @vbaranov, could you merge this, please?

**Comment by vbaranov** [comment]
Sure.

**Pull request merged**
