### PR TITLE
(Fix) tokens reservation update

### PR DESCRIPTION
**Pull request by vbaranov**
There are some problems with `ReservedTokensFinalizeAgent` and `MintableTokenExt`

**Problems**: 
1. Reserved tokens can be changed anytime during crowdsale
2. The array of reserved tokens is limited by 256 elements due to using `uint8` in loop.
3. If there are multiple addresses with reserved tokens in percents, percentage calculates incorrectly (`tokensSold` is increasing for every new reserved address).
4. Distributing of huge amount of reserved tokens can cause out gas problem for finalization of crowdsale.

**Solutions**: 
1. Reserved tokens can be set only once
2. Change the type in the loop to `uint256`.
3. prevent increasing of `tokensSold` in reserved tokens distribution to solve incorrect reservation in percents.
4. `distributeReservedTokens(uint reservedTokensDistributionBatch)` method is introduced to prevent out of gas problem on finalization. Method should be called by owner before finalization, if some tokens are reserved. Finalization cannot be called before all tokens are distributed. Method of distribution can be called many times with batches until all tokens won't be distributed.

Other improvements:
- remove 2 loops in reserved tokens distribution
- `isReserved` is added to `ReservedTokensData` structure to track, is address is reserved or not
- `isDistributed` is added to `ReservedTokensData` structure to track, did address get all reserved tokens or not
- rename `getReservedTokensListValInTokens` to `getReservedTokens`
- rename `getReservedTokensListValInPercentageUnit` to `getReservedPercentageUnit`
- rename `getReservedTokensListValInPercentageDecimals` to `getReservedPercentageDecimals`
- `isAddressReserved` method is added to `MintableTokenExt` contract to track, if address is reserved
- `areTokensDistributedForAddress` method is added to `MintableTokenExt` contract to track, if address got reserved tokens
- `finalizeReservedAddress` method is added to `MintableTokenExt` contract to mark, that address got all reserved tokens
- `reservedTokensDestinationsAreSet` method is added to `MintableTokenExt` contract to track, if reserved addresses are set or not
- tests are added and updated

### CODE REVIEW

**Comment by igorbarinov** [comment]
Victor, please submit PRs to audit repo also

**Comment by vbaranov** [comment]
@igorbarinov which repo do you mean? This https://github.com/poanetwork/ico-wizard-audit doesn't contain contract sources. Do you mean create PR, that will propose to change flat files https://github.com/poanetwork/ico-wizard-audit/tree/master/icowizard_Mainnet_0xa5F8fC0921880Cb7342368BD128eb8050442B1a1, right?

**Comment by igorbarinov** [comment]
Yes, this is the repository where Alex is doing audit. Any other ideas how to organize audit?

**Comment by vbaranov** [comment]
If Alex's entry point is Block Array live contracts, this is the only way.
But if he makes an audit of the ICO wizard contracts, the better way would be to audit sources from `wizard` branch of this repo.

**Pull request merged**
